name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test
      - run: npm run package

      - name: Find comment by body-includes
        uses: ./
        id: fc1
        with:
          issue-number: 1
          body-includes: search string 1
      - if: steps.fc1.outputs.comment-id != 620947762
        run: exit 1

      - name: Find comment by author
        uses: ./
        id: fc2
        with:
          issue-number: 1
          comment-author: retepsnave
      - if: steps.fc2.outputs.comment-id != 620947762
        run: exit 1

      - name: Find comment by body-includes and author
        uses: ./
        id: fc3
        with:
          issue-number: 1
          comment-author: peter-evans
          body-includes: search string 1
      - if: steps.fc3.outputs.comment-id != 620947858
        run: exit 1

      - name: No matching comment found
        uses: ./
        id: fc4
        with:
          issue-number: 1
          comment-author: peter-evans
          body-includes: this string will not be found
      - if: steps.fc4.outputs.comment-id != ''
        run: exit 1
