name: Test Find Comment
on: push
jobs:
  testFindComment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find Comment
        uses: ./
        id: fc1
        with:
          issue-number: 1
          body-includes: search string 1
      - if: steps.fc1.outputs.comment-id != 620947762
        run: exit 1

      - name: Find Comment
        uses: ./
        id: fc2
        with:
          issue-number: 1
          comment-author: peter-evans
          body-includes: search string 1
      - if: steps.fc2.outputs.comment-id != 620947858
        run: exit 1
